[package]
authors = ["Spanfile <spansdev@gmail.com>"]
edition = "2018"
name = "aoc-2020"
version = "0.1.0"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.9.0"
num = "0.3.1"
